### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *your function to illustrate*

In [4]:
# Example 1 - ### your explanation ###
### your code ###
#unsqueeze()
a=torch.tensor([[[1, 2, 3], [3, 4, 5]],[[5, 6, 7], [7, 8, 9]]])
a_unsqueeze = torch.unsqueeze(a,dim=1)
print(a.shape)
print(a_unsqueeze.shape)
a,a_unsqueeze

torch.Size([2, 2, 3])
torch.Size([2, 1, 2, 3])


(tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[5, 6, 7],
          [7, 8, 9]]]),
 tensor([[[[1, 2, 3],
           [3, 4, 5]]],
 
 
         [[[5, 6, 7],
           [7, 8, 9]]]]))

In [5]:
# Example 2 - ### your explanation ###
### your code ###
#squeeze()
a_squeeze = a_unsqueeze.squeeze(1)
print(a_squeeze.shape)
a_squeeze

torch.Size([2, 2, 3])


tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])

### Function 2 - your function to illustrate

In [6]:
# Example 1 - ### your explanation ###
### your code ###
#split
a = torch.arange(10).reshape(5,2)
a_1=torch.split(a,2)
a_2=torch.split(a,[2,3])
a,a_1,a_2

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 (tensor([[0, 1],
          [2, 3]]),
  tensor([[4, 5],
          [6, 7]]),
  tensor([[8, 9]])),
 (tensor([[0, 1],
          [2, 3]]),
  tensor([[4, 5],
          [6, 7],
          [8, 9]])))

In [7]:
# Example 2 - ### your explanation ###
### your code ###
#cat()資料串接
a=torch.tensor([[1,2,3]])
b=torch.tensor([[4,5,6]])
ab_0 = torch.cat((a,b),0)#0和1表示不同維度的拼接方法
ab_1 = torch.cat((a,b),1)
ba = torch.cat((b,a),0)
ab_0,ab_1,ba

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2, 3, 4, 5, 6]]),
 tensor([[4, 5, 6],
         [1, 2, 3]]))

### Function 3 - your function to illustrate

In [8]:
# Example 1 - ### your explanation ###
### your code ###
#reshape()
a=torch.tensor([[[1, 2, 3], [3, 4, 5]],[[5, 6, 7], [7, 8, 9]]])
a_re = torch.reshape(a,(4,3))
a_re

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]])

In [9]:
# Example 2 - ### your explanation ###
### your code ###
#view()
a=torch.tensor([[[1, 2, 3], [3, 4, 5]],[[5, 6, 7], [7, 8, 9]]])
print(a.view(4,3))
print(a.view(2,6))
print(a.view(1,12))

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]])
tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]])
tensor([[1, 2, 3, 3, 4, 5, 5, 6, 7, 7, 8, 9]])


### Function 4 - your function to illustrate

In [10]:
# Example 1 - ### your explanation ###
### your code ###
#dstack()
a=torch.tensor([[1,2,3]])
b=torch.tensor([[4,5,6]])
torch.stack((a,b))#增加新的維度進行堆疊

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [15]:
# Example 2 - ### your explanation ###
### your code ###
#take()
src = torch.tensor([[1,2,3],
                    [4,5,6],[7,8,9]])
#torch.take(src,torch.tensor([0,2,5]))
src.take(torch.tensor([0,2,5]))

tensor([1, 3, 6])